#include "UserData.h"

QStringList UserData::fieldLabels = QStringList()
        << QString::fromUtf8("类别")
        << QString::fromUtf8("商券")
        << QString::fromUtf8("归属")
        << QString::fromUtf8("帐号")
        << QString::fromUtf8("交密(同步)")
        << QString::fromUtf8("本金")
        << QString::fromUtf8("户名")
        << QString::fromUtf8("倒计时")
        << QString::fromUtf8("开始日")
        << QString::fromUtf8("支付到")
        << QString::fromUtf8("利息")
        << QString::fromUtf8("应付利息")
        << QString::fromUtf8("实付利息")
        << QString::fromUtf8("资密(同步)")
        << QString::fromUtf8("比例")
        << QString::fromUtf8("佣金")
        << QString::fromUtf8("状态")
        << QString::fromUtf8("备注")
        << QString::fromUtf8("预留 1")
        << QString::fromUtf8("预留 2")
        << QString::fromUtf8("预留 3")
        << QString::fromUtf8("预留 4")
        << QString::fromUtf8("预留 5")
        << QString::fromUtf8("预留 6");
